dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST = 127.0.0.1)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl)))
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
mybatis:
  type-aliases-package: com.caihao.entity
  # XML文件位置 指定DAO与SQL语句关联
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
